### ISSUE TITLE
Add restructure HDFS script

### ISSUE THREAD

**Issue by blootsvoets** [RADAR-CNS/RADAR-Docker#31]
The restructure script made in [Restructure-HDFS-topic](https://github.com/RADAR-CNS/Restructure-HDFS-topic) should be added here for convenience. Would fix RADAR-CNS/Restructure-HDFS-topic#1.

**Comment by sboettcher** [comment]
Regarding your solution in https://github.com/RADAR-CNS/Restructure-HDFS-topic/issues/1, yes it makes sense to run the jar in its own container, hadn't thought of that, and it works now thanks!

However I am still getting the same error as before in the beginning, here is an excerpt of the logging output. Not sure if this is at all relevant, and I guess this wasn't the problem I was having after all, but maybe it helps in adding this here:

<pre>
sebastian@moon:~/radar-docker$ docker run --rm --network hadoop -v "${OUT}:/output" -v "${JARJAR}:/${JAR}" -v "$HOME/log4j.properties:/log4j.properties" openjdk:8-jre-alpine java -Dlog4j.configuration=file:/log4j.properties -jar /${JAR} hdfs://hdfs-namenode:8020 /topicAndroidNew/$TOPIC /output
2017-04-24 17:37:57 INFO  RestructureAvroRecords:62 - 2017-04-24 17:37:57
2017-04-24 17:37:57 INFO  RestructureAvroRecords:63 - Starting...
2017-04-24 17:37:57 INFO  RestructureAvroRecords:64 - In:  hdfs://hdfs-namenode:8020/topicAndroidNew/android_empatica_e4_battery_level
2017-04-24 17:37:57 INFO  RestructureAvroRecords:65 - Out: /output
2017-04-24 17:37:57 DEBUG Shell:344 - Failed to detect a valid hadoop home directory
java.io.IOException: HADOOP_HOME or hadoop.home.dir are not set.
	at org.apache.hadoop.util.Shell.checkHadoopHome(Shell.java:326)
	at org.apache.hadoop.util.Shell.<clinit>(Shell.java:351)
	at org.apache.hadoop.util.StringUtils.<clinit>(StringUtils.java:80)
	at org.apache.hadoop.fs.FileSystem$Cache$Key.<init>(FileSystem.java:2823)
	at org.apache.hadoop.fs.FileSystem$Cache$Key.<init>(FileSystem.java:2818)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2684)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:172)
	at org.radarcns.RestructureAvroRecords.start(RestructureAvroRecords.java:121)
	at org.radarcns.RestructureAvroRecords.main(RestructureAvroRecords.java:71)
...
continues to process avro records
</pre>

**Comment by blootsvoets** [comment]
It's probably nothing. Admittedly, I didn't turn on debugging statements in my `log4j.properties`.  It shouldn't affect the rest of the execution, since that does not depend on HDFS being installed anywhere, only Java.

**Comment by blootsvoets** [comment]
Fixed in the dev branch. Call
```shell
./hdfs_restructure.sh /topicAndroidNew
```
to run the restructure script.
