### ISSUE TITLE
Register custom topics via schemas-tools in kafka-init

### ISSUE THREAD

**Issue by sboettcher** [RADAR-CNS/RADAR-Docker#79]
It might be nice to have a way of easily registering custom topics via the `kafka-init` mechanism. Part of that is already there, with the `etc/schema/` volume that gets merged. That way the topic can be created. However then the schemas-tools are missing the respective class for registering the topic with the schema-registry (see log).
What I did is building my own schemas-tools that include the class and loading those instead of the github release in the `Dockerfile`. But maybe this can be done in a nicer way? Unless I missed something that already implements that.

```
kafka-init_1                   | 2017-11-13T20:07:16.014342553Z [main] ERROR org.radarcns.schema.util.Utils - Failed to apply function, returning empty.
kafka-init_1                   | 2017-11-13T20:07:16.014729136Z java.lang.IllegalStateException: Topic android_eeg_sync_pulse schema cannot be instantiated
kafka-init_1                   | 2017-11-13T20:07:16.014874882Z 	at org.radarcns.config.AvroTopicConfig.parseAvroTopic(AvroTopicConfig.java:46)
kafka-init_1                   | 2017-11-13T20:07:16.014894100Z 	at org.radarcns.schema.specification.DataTopic.getTopics(DataTopic.java:61)
kafka-init_1                   | 2017-11-13T20:07:16.014904177Z 	at org.radarcns.schema.util.Utils.lambda$applyOrEmpty$0(Utils.java:112)
kafka-init_1                   | 2017-11-13T20:07:16.014927819Z 	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
kafka-init_1                   | 2017-11-13T20:07:16.014939647Z 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
kafka-init_1                   | 2017-11-13T20:07:16.014955428Z 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
kafka-init_1                   | 2017-11-13T20:07:16.014979859Z 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
kafka-init_1                   | 2017-11-13T20:07:16.014997257Z 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
kafka-init_1                   | 2017-11-13T20:07:16.015008452Z 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
kafka-init_1                   | 2017-11-13T20:07:16.015019391Z 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
kafka-init_1                   | 2017-11-13T20:07:16.015033303Z 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
kafka-init_1                   | 2017-11-13T20:07:16.015059088Z 	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
kafka-init_1                   | 2017-11-13T20:07:16.015070639Z 	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1620)
kafka-init_1                   | 2017-11-13T20:07:16.015086843Z 	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
kafka-init_1                   | 2017-11-13T20:07:16.015101537Z 	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
kafka-init_1                   | 2017-11-13T20:07:16.015115079Z 	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
kafka-init_1                   | 2017-11-13T20:07:16.015155521Z 	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
kafka-init_1                   | 2017-11-13T20:07:16.015190318Z 	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
kafka-init_1                   | 2017-11-13T20:07:16.015196351Z 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
kafka-init_1                   | 2017-11-13T20:07:16.015205266Z 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
kafka-init_1                   | 2017-11-13T20:07:16.015215939Z 	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
kafka-init_1                   | 2017-11-13T20:07:16.015242588Z 	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
kafka-init_1                   | 2017-11-13T20:07:16.015255832Z 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
kafka-init_1                   | 2017-11-13T20:07:16.015270802Z 	at java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:454)
kafka-init_1                   | 2017-11-13T20:07:16.015285701Z 	at org.radarcns.schema.registration.SchemaRegistry.registerSchemas(SchemaRegistry.java:74)
kafka-init_1                   | 2017-11-13T20:07:16.015301602Z 	at org.radarcns.schema.registration.SchemaRegistry$RegisterCommand.execute(SchemaRegistry.java:167)
kafka-init_1                   | 2017-11-13T20:07:16.015320640Z 	at org.radarcns.schema.CommandLineApp.main(CommandLineApp.java:191)
kafka-init_1                   | 2017-11-13T20:07:16.015454724Z Caused by: java.lang.IllegalArgumentException: Topic android_eeg_sync_pulse schema cannot be instantiated
kafka-init_1                   | 2017-11-13T20:07:16.015478518Z 	at org.radarcns.topic.AvroTopic.parse(AvroTopic.java:135)
kafka-init_1                   | 2017-11-13T20:07:16.015490273Z 	at org.radarcns.config.AvroTopicConfig.parseAvroTopic(AvroTopicConfig.java:44)
kafka-init_1                   | 2017-11-13T20:07:16.015513243Z 	... 26 more
kafka-init_1                   | 2017-11-13T20:07:16.015623872Z Caused by: java.lang.ClassNotFoundException: org.radarcns.passive.eegsync.EegSyncPulse
kafka-init_1                   | 2017-11-13T20:07:16.015651514Z 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
kafka-init_1                   | 2017-11-13T20:07:16.015673188Z 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
kafka-init_1                   | 2017-11-13T20:07:16.015698230Z 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
kafka-init_1                   | 2017-11-13T20:07:16.015730638Z 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
kafka-init_1                   | 2017-11-13T20:07:16.015744674Z 	at java.lang.Class.forName0(Native Method)
kafka-init_1                   | 2017-11-13T20:07:16.015760521Z 	at java.lang.Class.forName(Class.java:264)
kafka-init_1                   | 2017-11-13T20:07:16.015770986Z 	at org.radarcns.topic.AvroTopic.parse(AvroTopic.java:124)
kafka-init_1                   | 2017-11-13T20:07:16.015779249Z 	... 27 more
```

**Comment by blootsvoets** [comment]
Good point, it was the intention to do this, but it was not materialised in the docker file.

**Comment by sboettcher** [comment]
Fixed in https://github.com/RADAR-CNS/RADAR-Docker/pull/80.
